[build]
  command = NETLIFY_URL="https://shopify-next.netlify.app/" && npm run build
  publish = "build"

[dev]
  command = "npm run dev"
  framework = "#custom"
  port = 8888
  targetPort = 3000
  autoLaunch = true

[functions]
  directory = "functions/"