[build]
  command = "NETLIFY_URL=https://quickstark-lifefitness.netlify.app/ && npm run build"
  publish = "build"
  functions = "functions"

[dev]
  command = "npm run dev"
  framework = "#custom"
  port = 8888
  targetPort = 3000
  autoLaunch = true

[functions]
  directory = "functions/"